# Generated by Django 2.2.6 on 2019-10-29 21:42

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name_of_event', models.CharField(max_length=200, verbose_name='Name of event')),
                ('ticket_date_of_event', models.DateTimeField(verbose_name='Date of event')),
                ('ticket_price', models.IntegerField()),
                ('ticket_status', django_enumfield.db.fields.EnumField(default=2, enum=tickets.models.TicketStatus)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Name of user')),
                ('number_phone', models.CharField(max_length=12, verbose_name='Number of phone')),
                ('ticket_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
            ],
        ),
    ]
