# Generated by Django 2.2.6 on 2019-11-06 14:29

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_event', models.CharField(max_length=200, verbose_name='Name of event')),
                ('date_of_event', models.DateTimeField(verbose_name='Date of event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='username')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.IntegerField()),
                ('ticket_status', django_enumfield.db.fields.EnumField(default=2, enum=store.models.TicketStatus)),
                ('ticket_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Event')),
                ('ticket_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.User')),
            ],
        ),
    ]
