# Generated by Django 2.2.6 on 2019-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name_of_event',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name of event'),
        ),
    ]
