# Generated by Django 2.2.6 on 2019-11-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.User'),
        ),
    ]
